version: 0.2

phases:
  pre_build:
    commands:
      - echo -e 'Creating stack manager....'
      - rm -f $CONFIG_FILE
      - make deps
      - make deps-test
      - echo -e "scheduled_jobs:\n  aem_orchestrator:\n    stack_manager_pair:\n        stack_prefix:\t${BUILD_ID}-sm" > $CONFIG_FILE
      - cp $CONFIG_FILE $WORK_DIR

  build:
    commands:
      - make create-stack-manager stack_prefix=$BUILD_ID-sm config_path=$WORK_DIR
      - sh ./test/integration/fixtures/provision-test-dns-batch.sh $BUILD_ID

