version: 0.2

phases:
  pre_build:
    commands:
      - echo -e 'Creating stack manager....'
      - rm -f $CONFIG_FILE
      - echo -e "scheduled_jobs:\n  aem_orchestrator:\n    stack_manager_pair:\n        stack_prefix:" >> "${CONFIG_FILE}"
      - echo -e " ${BUILD_ID}-sm" >> "${CONFIG_FILE}"
      - cp $CONFIG_FILE $WORK_DIR

  build:
    commands:
      - echo -e 'Running make create-stack-manager "stack_prefix=$BUILD_ID-sm" config_path=stage/user-config/aem-stack-manager-sandpit/...'
      - make create-stack-manager stack_prefix=$BUILD_ID-sm config_path=$WORK_DIR
      - sh ./test/integration/fixtures/provision-test-dns-batch.sh $BUILD_ID

  post_build:
    commands:
      - rm -f $CONFIG_FILE
