version: 0.2

phases:
  pre_build:
    commands:
      - make deps
      - make deps-test
      - rm -f $CONFIG_FILE
      - echo -e "scheduled_jobs:\n  aem_orchestrator:\n    stack_manager_pair:\n        stack_prefix:\t${BUILD_ID}-sm" > $CONFIG_FILE
      - cp $CONFIG_FILE $WORK_DIR

  build:
    commands:
      - echo -e 'Creating AEM stack manager....'
      - make create-stack-manager stack_prefix=$BUILD_ID-sm config_path=$WORK_DIR

      # Provision test DNS records, needed for switch-dns testing against AEM Consolidated and AEM Full-Set environments
      - sh ./test/integration/fixtures/provision-test-dns-batch.sh $BUILD_ID
