version: 0.2

phases:
  pre_build:
    commands:
      - make deps
      - make deps-test
      - rm -f $CONFIG_FILE
      - echo -e "aws:\n  resources:\n    s3_bucket:"" ${BUILD_ID}-res" > $CONFIG_FILE
      - cp $CONFIG_FILE $WORK_DIR

  build:
    commands:
      - echo -e "Deleting CDN..."
      - make delete-cdn "stack_prefix=${BUILD_ID}-cdn" "config_path=stage/user-config/cdn-sandpit/"