version: 0.1

phases:
  pre_build:
    commands:
      - echo -e 'Testing consolidated...'
  build:
    commands:
      - echo -e 'Running make $BUILD_TARGETS "stack_prefix=$BUILD_ID-fs" "config_path=stage/user-config/aem-consolidated-$OS_TYPE-$AEM_VERSION/"'
