version: 0.2

phases:
  pre_build:
    commands:
      - echo -e 'Testing consolidated...'
      - make deps
      - make deps-test
      - echo -e "scheduled_jobs:\n  aem_orchestrator:\n    stack_manager_pair:\n        stack_prefix:\t${BUILD_ID}-sm" > ${CONFIG_FILE}
      - cp $CONFIG_FILE "stage/user-config/aem-consolidated-${OS_TYPE}-${AEM_VERSION}/"
      - make config "config_path=stage/user-config/aem-consolidated-${OS_TYPE}-${AEM_VERSION}/"
      - cp -R stage/descriptors/consolidated/* stage/

  build:
    commands:
      - echo -e 'Running make $BUILD_TARGETS "stack_prefix=${BUILD_ID}-con" "config_path=stage/user-config/aem-consolidated-${OS_TYPE}-${AEM_VERSION}/"'
#      - make create-consolidated "stack_prefix=${BUILD_ID}-con" "config_path=stage/user-config/aem-consolidated-${OS_TYPE}-${AEM_VERSION}/"
#      - cd stage/aem-stack-manager-messenger/ && make test-consolidated "stack_prefix=${BUILD_ID}-sm" "target_aem_stack_prefix=${BUILD_ID}-con" && cd ../../

  post_build:
    commands:
#      - make delete-consolidated "stack_prefix=${BUILD_ID}-con" "config_path=stage/user-config/aem-consolidated-${OS_TYPE}-${AEM_VERSION}/"



# cp "${integration_test_config_file}" "stage/user-config/aem-consolidated-${os_type}-${aem_version}/"
# echo "Configuring AEM Consolidated environment..."
# make config "config_path=stage/user-config/aem-consolidated-${os_type}-${aem_version}/"
# echo "Creating AEM Consolidated environment..."
# cp -R stage/descriptors/consolidated/* stage/
# make create-consolidated "stack_prefix=${test_id}-con" "config_path=stage/user-config/aem-consolidated-${os_type}-${aem_version}/"
# echo "Testing AEM Consolidated environment with AEM Stack Manager Messenger events..."
# cd stage/aem-stack-manager-messenger/ && make test-consolidated "stack_prefix=${test_id}-sm" "target_aem_stack_prefix=${test_id}-con" && cd ../../
# # TODO: temporarily disable switch-dns testing to allow CodeBuild to pass
# #       will re-enable when Ansible already upgrades boto sub dependency to boto3 for Route53 functionalities
# # echo "Testing DNS switching to point to AEM Consolidated environment..."
# # make switch-dns-consolidated config_path=stage/user-config/aws-resources-sandpit/ "stack_prefix=${test_id}-con" author_publish_dispatcher_hosted_zone=aemopencloud.cms "author_publish_dispatcher_record_set=${test_id}-apd-con"
# echo "Deleting AEM Consolidated environment..."
# make delete-consolidated "stack_prefix=${test_id}-con" "config_path=stage/user-config/aem-consolidated-${os_type}-${aem_version}/"
