---

AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  S3CMKAddManagedPolicyCondition:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
              - 6
              - Ref: AWSEncryptionParameters
          - 'overwrite-me'
  LambdaCMKAddManagedPolicyCondition:
    Fn::And:
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                  - 2
                  - Ref: AWSEncryptionParameters
              - 'overwrite-me'
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                  - 5
                  - Ref: AWSEncryptionParameters
              - 'overwrite-me'
  SNSCMKAddManagedPolicyCondition:
    Fn::And:
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                  - 1
                  - Ref: AWSEncryptionParameters
              - 'overwrite-me'
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                  - 3
                  - Ref: AWSEncryptionParameters
              - 'overwrite-me'
  DynamoDBCMKAddManagedPolicyCondition:
    Fn::And:
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                  - 0
                  - Ref: AWSEncryptionParameters
              - 'overwrite-me'
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                  - 4
                  - Ref: AWSEncryptionParameters
              - 'overwrite-me'
Description: Create Instance Profiles for AEM Stack Manager
Outputs:
  AEMStackManagerLambdaServiceRoleArn:
    Description: The Stack Manager Lambda Service Role ARN
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-StackManagerLambdaServiceRoleArn
    Value:
      Fn::GetAtt: AEMStackManagerLambdaServiceRole.Arn
  AEMStackManagerLambdaServiceRoleName:
    Description: The Stack Manager Lambda Service Role Name
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-StackManagerLambdaServiceRoleName
    Value:
      Ref: AEMStackManagerLambdaServiceRole
  AEMStackManagerSSMServiceRoleArn:
    Description: The Stack Manager SSM Service Role ARN
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-StackManagerSSMServiceRoleArn
    Value:
      Fn::GetAtt: StackmanagerSSMServiceRole.Arn
  AEMStackManagerSSMServiceRoleName:
    Description: The Stack Manager Lambda Service Role Name
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AemStackManagerSSMServiceRoleName
    Value:
      Ref: StackmanagerSSMServiceRole
Parameters:
  AWSEncryptionParameters:
    Description: |
      A list of AWS Encyrption parameters.
      List hast to be containing the following values in the following order:
        - KMS Key ID used for DynamoDB encryption
        - KMS Key ID used for SNS-Topic & SNS Queue encryption
        - KMS Key ARN used for Lambda function environment variable encryption
        - Managed Policy ARN for SNS  encryption
        - Managed Policy ARN for DynamoDB encryption
        - Managed Policy ARN for Lambda encryption
        - Managed Policy ARN for accessing S3 CMK
    Type: List<String>
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data file
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Main Resources Stack Prefix
    Type: String
  S3DataStackManagerPrefix:
    Description: Prefix within the Bucket to Locate Files
    Type: String
  CloudWatchS3StreamBucketNameParameter:
    Description: Bucket name that stores Stack data file
    Type: String
  CloudWatchS3StreamPrefixParameter:
    Description: Prefix within the Bucket to Locate Files
    Type: String
Resources:
  AEMStackManagerLambdaServiceRole:
    DependsOn: StackmanagerSSMServiceRole
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::If:
            - SNSCMKAddManagedPolicyCondition
            - Fn::Select:
                - 3
                - Ref: AWSEncryptionParameters
            - Ref: AWS::NoValue
        - Fn::If:
            - DynamoDBCMKAddManagedPolicyCondition
            - Fn::Select:
                - 4
                - Ref: AWSEncryptionParameters
            - Ref: AWS::NoValue
        - Fn::If:
            - LambdaCMKAddManagedPolicyCondition
            - Fn::Select:
                - 5
                - Ref: AWSEncryptionParameters
            - Ref: AWS::NoValue
        - Fn::If:
            - S3CMKAddManagedPolicyCondition
            - Fn::Select:
                - 6
                - Ref: AWSEncryptionParameters
            - Ref: AWS::NoValue
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ec2:Describe*
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:DeleteSnapshot
                  - autoscaling:Describe*
                  - autoscaling:UpdateAutoScalingGroup
                  - autoscaling:EnterStandby
                  - autoscaling:ExitStandby
                  - autoscaling:SuspendProcesses
                  - autoscaling:ResumeProcesses
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:*
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:s3:::${DataBucketNameParameter}/${S3DataStackManagerPrefix}/*
              - Action:
                  - s3:*
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:s3:::${CloudWatchS3StreamBucketNameParameter}/${CloudWatchS3StreamPrefixParameter}/*
              - Action:
                  - ssm:SendCommand
                  - ssm:CancelCommand
                Effect: Allow
                Resource: '*'
              - Action:
                  - iam:PassRole
                Effect: Allow
                Resource:
                  Fn::GetAtt: StackmanagerSSMServiceRole.Arn
            Version: 2012-10-17
          PolicyName: StackManagerPolicy
      RoleName:
        Fn::Sub: ${MainStackPrefixParameter}-AEMStackManagerLambdaRole
    Type: AWS::IAM::Role
  StackmanagerSSMServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - Fn::If:
            - SNSCMKAddManagedPolicyCondition
            - Fn::Select:
                - 3
                - Ref: AWSEncryptionParameters
            - Ref: AWS::NoValue
        - Fn::If:
            - S3CMKAddManagedPolicyCondition
            - Fn::Select:
                - 6
                - Ref: AWSEncryptionParameters
            - Ref: AWS::NoValue
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:*
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:aws:s3:::${DataBucketNameParameter}/${S3DataStackManagerPrefix}/SSMOutput/*
            Version: 2012-10-17
          PolicyName: AemBackupPolicy
      RoleName:
        Fn::Sub: ${MainStackPrefixParameter}-AEMStackManagerSSMRole
    Type: AWS::IAM::Role
