AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  UseCMKSNSEncryptionCondition:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
            - 3
            - Ref: AWSEncryptionParameters
          - 'overwrite-me'
Description: Create Messaging resources for the AEM Stack Auto Scaling Group Events
Outputs:
  AEMASGEventQueueName:
    Description: The AEM ASG Event Queue Name
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventQueueName
    Value:
      Fn::GetAtt: AEMAutoScalingGroupEventQueue.QueueName
  AEMASGEventTopic:
    Description: The AEM ASG Event Topic
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventTopic
    Value:
      Ref: AEMASGEventTopic
  AEMAutoScalingGroupEventQueue:
    Description: The AEM ASG Event Queue
    Value:
      Ref: AEMAutoScalingGroupEventQueue
  CriticalAlarmNotificationTopic:
    Description: The AEM Alarm Notification Topic
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
    Value:
      Ref: CriticalAlarmNotificationTopic
  WarningAlarmNotificationTopic:
    Description: The AEM Alarm Notification Topic
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
    Value:
      Ref: WarningAlarmNotificationTopic
Parameters:
  AEMASGEventQueueNameParameter:
    Description: The AEM Stack Auto Scaling Group Event Quene Name
    Type: String
  AEMASGEventTopicDisplayNameParameter:
    Description: The AEM Stack Auto Scaling Group Event Topic Display Name
    Type: String
  AEMASGEventTopicNameParameter:
    Description: The AEM Stack Auto Scaling Group Event Topic Name
    Type: String
  AEMCWEventNotificationEmail:
    Description: The EMail adress for sending CW Alarm messages
    Type: String
  AWSEncryptionParameters:
    Description: |
      A list of AWS Encyrption parameters.
      List hast to be containing the following values in the following order:
        - Boolean for enabling/disabling EBS Volume encryption
        - KMS Key ID used for EBS Volume encryption
        - Managed Policy ARN for EBS Volume encryption
        - KMS Key ID used for SNS-Topic & SNS Queue encryption
        - Managed Policy ARN for SNS-Topic & SNS Queue encryption
        - KMS Key ID used for Lambda encryption
        - Managed Policy ARN for Lambda encryption
        - Managed Policy ARN for accessing S3 CMK
    Type: List<String>
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
Resources:
  CriticalAEMASGEventQueueLengthHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Ref: CriticalAlarmNotificationTopic
      AlarmDescription: Alarm if queue length avg > 10 for 2 minutes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: QueueName
        Value:
          Ref: AEMASGEventQueueNameParameter
      EvaluationPeriods: 2
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 60
      Statistic: Average
      Threshold: 10
      TreatMissingData: ignore
    Type: AWS::CloudWatch::Alarm
  AEMASGEventQueuePolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - sqs:SendMessage
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: AEMASGEventTopic
          Effect: Allow
          Principal:
            AWS: '*'
          Resource:
          - Fn::GetAtt:
            - AEMAutoScalingGroupEventQueue
            - Arn
        Version: '2012-10-17'
      Queues:
      - Ref: AEMAutoScalingGroupEventQueue
    Type: AWS::SQS::QueuePolicy
  AEMASGEventTopic:
    Properties:
      KmsMasterKeyId:
          Fn::If:
          - UseCMKSNSEncryptionCondition
          - Fn::Select:
              - 3
              - Ref: AWSEncryptionParameters
          - Ref: AWS::NoValue
      DisplayName:
        Ref: AEMASGEventTopicDisplayNameParameter
      Subscription:
      - Endpoint:
          Fn::GetAtt:
          - AEMAutoScalingGroupEventQueue
          - Arn
        Protocol: sqs
      TopicName:
        Ref: AEMASGEventTopicNameParameter
    Type: AWS::SNS::Topic
  AEMAutoScalingGroupEventQueue:
    Properties:
      KmsMasterKeyId:
          Fn::If:
          - UseCMKSNSEncryptionCondition
          - Fn::Select:
              - 3
              - Ref: AWSEncryptionParameters
          - Ref: AWS::NoValue
      QueueName:
        Ref: AEMASGEventQueueNameParameter
      VisibilityTimeout: 60
    Type: AWS::SQS::Queue
  WarningAlarmNotificationTopic:
    Properties:
      KmsMasterKeyId:
          Fn::If:
          - UseCMKSNSEncryptionCondition
          - Fn::Select:
              - 3
              - Ref: AWSEncryptionParameters
          - Ref: AWS::NoValue
      DisplayName:
        Fn::Sub:
          - "${PrerequisitesStackPrefixParameter}-Warning-Utilities-alarm-notification-topic"
          - PrerequisitesStackPrefixParameter:
              Ref: 'PrerequisitesStackPrefixParameter'
      Subscription:
        - Endpoint:
            Ref: AEMCWEventNotificationEmail
          Protocol: email
        - Ref: AWS::NoValue
    Type: AWS::SNS::Topic
  CriticalAlarmNotificationTopic:
    Properties:
      KmsMasterKeyId:
          Fn::If:
          - UseCMKSNSEncryptionCondition
          - Fn::Select:
              - 3
              - Ref: AWSEncryptionParameters
          - Ref: AWS::NoValue
      DisplayName:
        Fn::Sub:
          - "${PrerequisitesStackPrefixParameter}-Critical-Utilities-alarm-notification-topic"
          - PrerequisitesStackPrefixParameter:
              Ref: 'PrerequisitesStackPrefixParameter'
      Subscription:
        - Endpoint:
            Ref: AEMCWEventNotificationEmail
          Protocol: email
        - Ref: AWS::NoValue
    Type: AWS::SNS::Topic
